INSERT INTO USER(USER_ID, PASSWORD, NAME, EMAIL) VALUES('james', '1234', '이호영', 'yihoyoung@nate.com');
INSERT INTO USER(USER_ID, PASSWORD, NAME, EMAIL) VALUES('james1', '1234', '이호영2', 'yihoyoung1@nate.com');
INSERT INTO QUESTION(ID, TITLE, CONTENTS, WRITER_ID, CREATE_DATE, COUNT_OF_ANSWER) VALUES(1, 'james is good man.', 'HELLO, WORLD.', 1, CURRENT_TIMESTAMP(), 0);